# Numpy Tutorial 
## 楊家融
### Radiologist Programmer

In [1]:
import numpy as np

## Array initialize 

In [2]:
# Literal
np.array([[1, 2], [3, 4], [5, 6]])

array([[1, 2],
       [3, 4],
       [5, 6]])

In [3]:
# Zeros
np.zeros(shape=(3, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [4]:
# Ones
np.ones(shape=(3, 2), dtype=np.float64)

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [5]:
# Random
np.random.rand(3, 2) # between 0-1

array([[0.09381849, 0.91030667],
       [0.65621606, 0.42584894],
       [0.89497123, 0.18301834]])

In [6]:
# Random (random distribution)
np.random.randn(3, 2) # between -1~1

array([[-0.11008067,  0.80769125],
       [-1.33517195, -0.35932455],
       [-0.64906562, -1.58026627]])

## Operation

In [7]:
# Transpose
np.array([[1, 2], [3, 4], [5, 6]]).T

array([[1, 3, 5],
       [2, 4, 6]])

In [8]:
a = np.array([[1, 2], [3, 4], [5, 6]])
b = np.array([[0.1, 0.2], [0.3, 0.4], [0.5, 0.6]])
a + b

array([[1.1, 2.2],
       [3.3, 4.4],
       [5.5, 6.6]])

In [9]:
a - b

array([[0.9, 1.8],
       [2.7, 3.6],
       [4.5, 5.4]])

In [10]:
a * b

array([[0.1, 0.4],
       [0.9, 1.6],
       [2.5, 3.6]])

In [11]:
a / b

array([[10., 10.],
       [10., 10.],
       [10., 10.]])

In [12]:
a.dot(b)

ValueError: shapes (3,2) and (3,2) not aligned: 2 (dim 1) != 3 (dim 0)

In [13]:
a.T.dot(b)

array([[3.5, 4.4],
       [4.4, 5.6]])

## Broadcasting

In [14]:
a = np.zeros((3, 2))

In [15]:
a + 1

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [16]:
a + [1, 2]

array([[1., 2.],
       [1., 2.],
       [1., 2.]])

In [17]:
a + [1, 2, 3]

ValueError: operands could not be broadcast together with shapes (3,2) (3,) 

In [18]:
a + [[1], [2], [3]]

array([[1., 1.],
       [2., 2.],
       [3., 3.]])

## Concat

In [19]:
a

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [20]:
b

array([[0.1, 0.2],
       [0.3, 0.4],
       [0.5, 0.6]])

In [21]:
np.concatenate((a, b))

array([[0. , 0. ],
       [0. , 0. ],
       [0. , 0. ],
       [0.1, 0.2],
       [0.3, 0.4],
       [0.5, 0.6]])

In [22]:
np.concatenate((a, b), axis=1)

array([[0. , 0. , 0.1, 0.2],
       [0. , 0. , 0.3, 0.4],
       [0. , 0. , 0.5, 0.6]])

In [23]:
b>0

array([[ True,  True],
       [ True,  True],
       [ True,  True]])

## Boolean

In [24]:
b > 0.3

array([[False, False],
       [False,  True],
       [ True,  True]])

## Select

In [25]:
b[b > 0.3]

array([0.4, 0.5, 0.6])

In [26]:
b

array([[0.1, 0.2],
       [0.3, 0.4],
       [0.5, 0.6]])

In [27]:
b[1:3][:]

array([[0.3, 0.4],
       [0.5, 0.6]])

## Update

In [28]:
b[1:3][:] = 1

In [29]:
b

array([[0.1, 0.2],
       [1. , 1. ],
       [1. , 1. ]])

## Speed

In [30]:
import random
def random_walk(n):
    position = 0
    walk = [position]
    for i in range(n):
        position += 2*random.randint(0, 1)-1
        walk.append(position)
    return walk

random_walk(1000)

[0,
 1,
 2,
 1,
 0,
 1,
 2,
 3,
 4,
 3,
 2,
 1,
 2,
 1,
 0,
 1,
 0,
 1,
 2,
 3,
 2,
 1,
 0,
 -1,
 0,
 -1,
 -2,
 -1,
 0,
 1,
 0,
 1,
 2,
 1,
 2,
 1,
 0,
 -1,
 -2,
 -1,
 -2,
 -3,
 -4,
 -3,
 -2,
 -1,
 0,
 -1,
 -2,
 -1,
 -2,
 -1,
 0,
 -1,
 -2,
 -1,
 -2,
 -1,
 0,
 -1,
 -2,
 -1,
 -2,
 -3,
 -2,
 -3,
 -4,
 -5,
 -6,
 -7,
 -6,
 -5,
 -4,
 -3,
 -4,
 -3,
 -2,
 -1,
 0,
 -1,
 -2,
 -3,
 -2,
 -3,
 -4,
 -5,
 -6,
 -5,
 -6,
 -5,
 -4,
 -3,
 -4,
 -3,
 -2,
 -1,
 0,
 1,
 0,
 -1,
 0,
 -1,
 -2,
 -3,
 -4,
 -3,
 -4,
 -3,
 -4,
 -5,
 -4,
 -5,
 -6,
 -5,
 -6,
 -7,
 -6,
 -5,
 -6,
 -7,
 -6,
 -7,
 -8,
 -9,
 -10,
 -9,
 -10,
 -9,
 -8,
 -7,
 -8,
 -9,
 -10,
 -9,
 -8,
 -9,
 -10,
 -9,
 -8,
 -7,
 -6,
 -5,
 -6,
 -7,
 -8,
 -7,
 -6,
 -7,
 -8,
 -7,
 -6,
 -7,
 -8,
 -9,
 -10,
 -11,
 -10,
 -9,
 -8,
 -9,
 -10,
 -11,
 -10,
 -9,
 -8,
 -7,
 -6,
 -5,
 -6,
 -5,
 -6,
 -7,
 -8,
 -9,
 -8,
 -7,
 -6,
 -7,
 -8,
 -7,
 -8,
 -7,
 -8,
 -7,
 -6,
 -5,
 -6,
 -7,
 -8,
 -7,
 -8,
 -9,
 -10,
 -11,
 -12,
 -11,
 -12,
 -11,
 -10,
 -9,
 -10,
 -9,
 -8,
 -7,
 -6

In [33]:
%%timeit 
random_walk(1000)

1.56 ms ± 22.2 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [34]:
from itertools import accumulate
def random_walk_faster(n=1000):
    steps = random.choices([-1,+1], k=n)
    return [0]+list(accumulate(steps))

In [35]:
%%timeit
random_walk_faster(1000)

274 µs ± 6.99 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [36]:
def random_walk_fastest(n=1000):
    # No 's' in numpy choice (Python offers choice & choices)
    steps = np.random.choice([-1,+1], n)
    return np.cumsum(steps)

In [37]:
%%timeit
random_walk_fastest(1000)

24 µs ± 1.17 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


## No Homework
